name: ci
on:
  pull_request:
    types: ["opened", "synchronize", "reopened", "edited"]
  workflow_dispatch:

jobs:
  linting-and-formatting-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - run: npm run test-all
