on:
  pull_request:
    branches:
      - main
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    types:
      - closed

name: Create Release

jobs:
  build:
    name: Create Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }} # Created my own PAT
        with:
          tag_name: v1.1.0
          release_name: v1.1.0
          body: |
            Feat: Added The Mandalorian API to the projects list.
          draft: false
          prerelease: false
